version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hometeam_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hometeam_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "pg_data:/data"

volumes:
  pg_data: